# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVSGgeS8bDoEoM766xASkmxOSkW2CcI3
"""

print("To know about anything click below number")
print("1) For E.G.S Pillay Engineering College")
# print("2) For E.G.S Pillay Arts/Science College")
ginst=int(input("Enter Your Option: "))

if ginst == 1:
    print("Welcome To E.G.S P\n")
    print("1) Dept")
    print("2) Admi")
    print("3) Hostel")
    print("4)Transport ")
    print("5) End")

    A1=int(input("Enter Your Option: "))
    if A1==1:
        print("1) AI&DS")
        print("2) CSE")
        print("3) EEE")
        print("4) BME")
        print("5) MACH")
        print("6)CS&BS")
        print("7)CIVIL")
        print("8)ECE")
        dep=int(input("Enter Your Option: "))
        if dep==1:
            print("Welcome To The ai&ds\n")
            print("1) staff")
            print("2) Year")

            aids=int(input("Enter Your Option: "))
            if aids == 1:
                print("dr.S.Palanimurugan | HOD Ai&ds | Academic Director | Cell: 1234567890 | mail - palani123@gmail.com")
                print("Mr.R.Gopi | Asst Prof Ai&ds  | Cell: 9715303637 | mail - gopi23@gmail.com")
                print(" dr.j.Amutha|asst HOD Ai&ds |  Cell: 7708549612| mail - palani123@gmail.com")
                print(" Ms.Ragapriya|asst proffeser Ai&ds |  Cell: 7708549612| mail - palani123@gmail.com")
                print(" Ms.Agilantashvari|asst proffeser Ai&ds |  Cell: 7708549612| mail - palani123@gmail.com")
                print(" Ms.diveyabarathi|asst HOD Ai&ds |  Cell: 7708549612| mail - palani123@gmail.com")
                print(" Ms.Anushiya|asst HOD Ai&ds |  Cell: 7708549612| mail - palani123@gmail.com")
            elif aids == 2:
                print("1) 1st year ")
                print("2) 2nd year ")
                print("3) 3rd year ")
                print("4) 4th year ")
                yr=int(input("enter your option:"))
                if yr==1:
                    print("sem-1:\n 1)2301IP101: Induction Program\n 2)2301MA101 Engineering Mathematics –I\n  3)2302AS101: Fundamentals of Data Science\n 4)2301GEX01: Foundation of Electrical and Electronics Engineering\n 5)2301GEX02: Engineering Graphics and Design\n 6)2301GEX03: Problem Solving using C\n 7)2301TA101: Tamil and Technology\n 8)2304FLX01: Foreign Language\n 9)2301GEX51: Computer Practices Laboratory\n 10) 2301LS101: Life Skill Activity – I")
                    print("sem-2\n 1)2301MA201: Numerical Computing\n 2)2301PH201: Fundamentals of Physics\n 3)2301CH201: Applied Chemistry in Informatic\n 4)2301GE201: Programming using Python\n 5)2301GE202: Data Structure Concepts\n 6)2301ENX01: Professional English\n 7)2301ENX01: Professional English\n\n LABORATORY COURSE:\n 1)2301PHX51: Engineering Physics Laboratory\n2)2301CHX51: Engineering Chemistry Laboratory\n 3)2301ENX51: Communication Skills Laboratory\n 4)2301GEX52: Engineering Practices Laboratory\n 5)2301LS201 Life Skills – II  ")
                elif yr==2:
                    print("sem3:\n 1)2301HSX01:  Universal Human Values & Ethics\n 2)2301MA301:  Probability & Statistics\n 3)2301GEX05:  Applied Digital Logic & Design\n 4)2302AS301: Design and Analysis of Algorithms\n 5)2302AS302: Database Systems\n 6)2302AS303: Artificial Intelligence\n\n LABORATORY COURSE:\n 1)2301GEX54:Applied Digital Logic & Design Laboratory\n 2)2302AS351: Statistical Analysis and Computing\n 3)2302AS352: SQL for Data Science\n 4)2304GE301:Professional Development Course - I\n 5)2301LS301 Life Skills – II ")
                    print("sem-4\n 1)2301GEX07: Environmental Sciences & Sustainability\n 2)2301MA401: Discrete Mathematics & Graph Theory\n 3)2302AS401: Software Engineering\n 4)2302AS402: Data Mining Concepts\n5)2302AS403: Data Analytics and Visualization\n6)2302AS404: Machine Learning Techniques\nLABORATORY COURSES:\n\n 1)2302AS451: Data Mining Laboratory\n 2)2302AS452: Machine Learning Laboratory\n 3)2301MC403: Mandatory Course - I - Innovation & Entrepreneurship Fundamentals\n 4)2304GE401: Professional Development Course - II\n 5)2301LS401: Life Skills – IV ")
                elif yr==3:
                    print(" sem-5:\n  " )
                    print("sem-6:\n ")
        elif dep == 2:
            print("Welcome To The  CSE\n")
            print("1) staff")
            print("2) Year")

            CSE = int(input("Enter Your Option: "))
            if  CSE  == 1:
                print( "dr. manivannan| HOD CSE|  Cell:  6379072276| mail -mani123@gmail.com")
                print("Mr.kannan | Asst Prof CSE  | Cell: 9715303637 | mail - kannan23@gmail.com")
                print(" dr.sugumaran|asst HOD CSE |  Cell: 7708549612| mail - sugumaran125@gmail.com")
            elif CSE == 2:
                 print("1) 1st year ")
                 print("2) 2nd year ")
                 print("3) 3rd year ")
                 print("4) 4th year ")
            yr1 = int(input("enter your option:"))
            if yr1 == 1:
                print("sem-1:-\n 1)2301IP101: Induction Program\n 2)2301MA104: Engineering Mathematics – I\n 3)2301GEX01 Foundation of Electrical and Electronics Engineering\n 4)2301GEX02: Engineering Graphics and Design\n 5)2301GEX05: Applied Digital Logic and Design\n 6)2301TA101: Tamil and Technology\n 7)2304FLX01: Foreign Language")
                print("sem-2:-\n ")
            elif yr1 == 2:
                print("sem3 1)engineering mathematics-3\n2)DPT\n3)cod\n4)dbms\n 5)big data\n 6)python\n 7)wen technology\n\n LABORATORY COURSE:-1)Data Structures Laboratory\n 2)Object OrientedProgrammingLaboratory\n 3)Life Skills: Soft Skills")
                print("sem-4 1)em-4\n2)os\n3)ai\n4)dv\n5)dm\n\n LABORATORY COURSE:-\n 1)Networks Laboratory\n 2)Operating System Laboratory\n 3)Database Management Systems Laboratory\n ")
            elif  yr1 == 3:
                print("sem-5:-\n1)Discrete Mathematics\n 2)Object Oriented Analysis and Design\n 3)Theory of Computation\n 4)Essence of Indian Traditional Knowledge\n\nLABORATORY COURSE:-\n 1)CASE Tools Laboratory\n 2)Mobile Application Development Laboratory")
                print("sem-6:\n1)Compiler Design\n 2)Web Technology\n 3)Artificial Intelligence\n 4)PC Elective II – Distributed Systems / Adhoc & Sensor Networks\n 5)HSS Elective II – Business Model Innovation 6) open elective I \n\n LABORATORY COURSE:-1)Compiler Laboratory\n2)Web Technology Laboratory\n 3)Software Prototype development Lab (Mini Project 1)\n 4)Industrial Visit Presentation\n 5)Life Skills: Aptitude II ")
            elif yr1 == 4:
                print("sem-7:\n1)Cloud Computing\n 2)Cryptography and Network Security\n 3)Universal Human Values and Ethics\n\nLABORATORY COURSE:-1)Cloud Computing Laboratory\n 2)Network Security Laboratory\n3)Software Development Laboratory (Mini Project II)\n 4)Life Skills: Comprehensive Viva\n 5)In plant training/Internship")
                print("sem-8:\n1)PC Elective IV-Service Oriented Architecture\n 2)PC Elective V – Data Centre and Virtualization\n\n LABORATORY COURSE:-1)Project Work")
        elif dep == 3:
            print(" welcome to the EEE")
            print("1)staff")
            print("2)year")
            EEE = int(input("enter your option:"))
            if EEE == 1:
                print(" staff details")
            elif EEE == 2:
                print("1) 1st year")
                print("2) 2nd year")
                print("3) 3rd year")
                print("4) 4th year")

            yr2= int(input("enter your option"))
            if yr2 == 1:
                print("sem-1:\n 1)Engineering Mathematics – I (Calculus and Differential Equations)\n 2)Wave, Optics and Electromagnetism\n 3)Electric Circuit Analysis\n4)Engineering Graphics\n LABORATORY COURSE:\n\n 1)CAD Laboratory\n 2)Basic Electrical and Electronics Engineering Lab\n 3)Engineering Physics Lab\n 4)Engineering Intelligence-I")
                print("sem-2:\n1)Engineering Mathematics – II (Linear Algebra, Transform Calculus and Numerical Methods)\n 2)Applied Chemistry\n 3)Programming for Problem Solving\n 4)English for Engineers\n 5)Engineering Exploration\n LABORATORY COURSE:\n\n 1)Engineering Chemistry Lab\n 2)Basic Workshop Lab \n 3)Computer Programming Lab\n 4)Communication Skill Lab\n 5)Engineering Intelligence - II")
            elif yr2 == 2:
                print("sem-3:\n 1)Engineering Mathematics III  (Complex Variables, Vector Calculus and Transforms)\n 2)Analog Electronics\n 3)Digital Electronics\n 4)DC Machines and Transformers\n 5)Basic Civil and Mechanical Engineering\n LABORATORY COURSE:\n\n1)Analog Electronics Laboratory\n 2)DC Machines and Transformers Laboratory\n 3)Life Skills: Soft Skill\n4)Audit Course:Constitution of India")
                print("sem-4:\n 1)Generation, Transmission and Distribution\n 2)Synchronous and Asynchronous Machines\n 3)Linear Integrated Circuits\n4)Communication Engineering\n 5)Biology for Engineers\n LABORATORY COURSE:\n\n1)Synchronous and Asynchronous Machines Laboratory\n 2)Analog and Digital Integrated Circuits Laboratory\n 3)Analog and Digital Integrated Circuits Laboratory\n4)Mandatory Course:Environmental Science")
            elif yr2 == 3:
                print("sem-5:\n 1)Measurements and Instrumentation\n 2)Linear Control Systems\n 3)Power Electronics\n 4)Object Oriented Programming\n 5)Professional Elective-I (Electrical Machine Design)\n LABORATORY COURSE:\n\n 1)Control and Instrumentation Laboratory\n 2)Mini Project – I\n 3)Object Oriented Programming Laboratory\n 4) Life Skills: Aptitude- I")
                print("sem-6:\n1)Solid State Drives\n 2)Power System Analysis\n 3)Microprocessors and Microcontrollers\n 4)Elective-II (PEC-II) \n 5)Elective-III (HSSC Elective-I)\n 6)Elective-IV (Open Elective-I\n LABORATORY COURSE:\n\n 1)Power Electronics and Drives Laboratory\n 2)Microprocessors and Microcontrollers Laboratory\n 3)Mini Project-II\n 4)Life Skills: Aptitude- II\n 5)Industrial Visit Presentation ")
            elif yr2 == 4:
                print("sem-7:\n 1)Universal Human Values and Ethics\n 2)Power System Operation and Control\n 3)Elective-V (PEC-III)( Electrical Energy Generation Utilization And Conservation)\n 4)Elective-VI (HSSC Elective-II)( Innovation & Entrepreneurship Fundamentals )\n 5)Elective-VII (HSSC Elective-III)( Design Thinking For Innovation)\n 6)Elective-VIII (Open Elective-II)\n 7)Power System Simulation Laboratory\n 8)Life Skills: Comprehensive Viva\n 9)In plant / Internship Training Presentation")
                print("sem-8:\n 1)Elective-IX (PEC-IV) Flexible AC Transmission Systems\n 2) Elective-X (PEC-V) High Voltage Engineering\n 3)Project Work")
        elif dep ==4:
            print("welcom to BME")
            print("1) staff")
            print("2)year")
            BME = int(input("enter your option: "))
            if BME == 1:
                print("staf details")
            elif BME ==2:
                print("1) 1st year ")
                print("2) 2nd year")
                print("3) 3rd year")
                print("4) 4th year")
                yr3=int(input("enter your option: "))
            if yr3==1:
                print(" sem-1:\n")
                print(" sem-2:\n")
            elif yr3==2:
                print("sem-3:\n")
                print("sem-4:\n")
            elif yr3 == 3:
                print("sem-5:\n")
                print("sem-6:\n")
            elif yr3 ==4:
                print("sem-7:\n")
                print("sem-8:\n")
        elif dep == 5:
            print("welcom to MECH")
            print("1)staff")
            print("2)year")
            MECH = int(input("enter your option: "))
            if MECH == 1:
                print("staff detail")
            elif MECH ==2:
                print(" 1) 1st year")
                print("2) 2nd year")
                print("3) 3rd year")
                print("4) 4th year")
                yr4 = int(input("enter your option:"))
                if yr4 ==1:
                    print(" sem-1:\n")
                    print(" sem-2:\n")
                elif yr4 ==2:
                    print("sem-3:\n")
                    print("sem-4:\n")
                elif yr4==3:
                    print("sem-5\n")
                    print("sem-6\n")
                elif yr4==4:
                    print("sem-7:\n")
                    print("sem-8:\n")
        elif dep == 6:
            print("welcome to CS&BS")
            print("1)staff")
            print("2)year")
            CS_BS = int(input("enter you option:"))
            if  CS_BS == 1:
                print("staff detail")
            elif  CS_BS == 2:
                print("1) 1st year")
                print("2) 2nd year")
                print("3) 2nd year")
                print("4) 2nd year")
                yr5 = int(input("enter your option:"))
                if yr5 == 1:
                    print("sem-1:\n")
                    print("sem-2:\n")
                elif yr5 == 2:
                    print("sem-3:\n")
                    print("sem-4:\n")
                elif yr5 == 3:
                    print("sem-5:\n")
                    print("sem-6:\n")
                elif yr5 == 4:
                    print("sem-7:\n")
                    print("sem-8:\n")
        elif dep == 7:
            print("welcome to the CIVIL")
            print("1)staff")
            print("2)year")
            CIVIL = int(input("enter your option:"))
            if CIVIL ==1:
                print("staff")
            elif CIVIL ==2:
                print("1 ) 1st year")
                print("2) 2nd year")
                print("3) 3rd year")
                print("4 ) 4th year")
                yr6=int(input("enter your option:"))
                if yr6==1:
                    print("")
                    print("")
                elif yr6==2:
                    print("")
                    print("")
                elif yr6==3:
                    print("")
                    print("")
                elif yr6==4:
                    print("sem-7:\n")
                    print(" sem-8:\n")
        elif dep ==8:
           print("welcome to ECE ")
           print("1)staff")
           print("2)year")
           ECE =int(input("enter your option:"))
           if ECE==1:
               print("staff details")
           elif ECE==2:
               print("1)1st year")
               print("2)2ndyear")
               print("3)3rd year")
               print("4)4th year")
               yr7 = int(input("enter your option:"))
               if yr7==1:
                   print("sem-1:\n")
                   print("sem-2:\n")
               elif yr7==2:
                   print("sem-3:\n")
                   print("sem-4:\n")
               elif yr7==3:
                   print("sem-5:\n")
                   print("sem-6:\n")
               elif yr7==4:
                   print("sem-7:\n")
                   print("sem-8:\n")
               else:
                   print('')
        elif dep==9:
           print("welcome to IT")
           print("1)staff")
           print("2)year")
           IT = int(input("enter your option:"))
           if IT==1:
               print("staff details")
           elif IT==2:
                print("1)1st year")
                print("2)2nd year")
                print("3)3rd year")
                print("4) 4th year")
                yr8=int(input("enter your option:"))
                if yr8==1:
                    print("sem-1:\n")
                    print("sem-2:\n")
                elif yr8==2:
                   print("sem-3:\n")
                   print("sem-4:\n")
                elif yr8==3:
                    print("sem-5:\n")
                    print("sem-6:\n")
                elif yr8==4:
                  print("sem-7:\n")
                  print("sem-8:\n")
else:
    print("None")